### ISSUE TITLE
Error when build ANDROID - Unable to start activity 

### ISSUE THREAD

**Issue by danielrf121** [rdlabo/capacitor-facebook-login#27]
Good Morning. I am finding problems to build for android in the latest version for capactior 2.0.0.
Apparently some error in **"androidx.coordinatorlayout.widget.CoordinatorLayout"**

`2020-04-06 22:25:05.233 11377-11377/br.com.bichoramaapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.bichoramaapp, PID: 11377
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.bichoramaapp/br.com.bichoramaapp.MainActivity}: android.view.InflateException: Binary XML file line #2 in br.com.bichoramaapp:layout/bridge_layout_main: Binary XML file line #2 in br.com.bichoramaapp:layout/bridge_layout_main: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3447)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7777)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
     Caused by: android.view.InflateException: Binary XML file line #2 in br.com.bichoramaapp:layout/bridge_layout_main: Binary XML file line #2 in br.com.bichoramaapp:layout/bridge_layout_main: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
     Caused by: android.view.InflateException: Binary XML file line #2 in br.com.bichoramaapp:layout/bridge_layout_main: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout
     Caused by: java.lang.ClassNotFoundException: androidx.coordinatorlayout.widget.CoordinatorLayout
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.getcapacitor.BridgeActivity.init(BridgeActivity.java:54)
        at br.com.bichoramaapp.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:7981)
        at android.app.Activity.performCreate(Activity.java:7970)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3594)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2146)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7777)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
2020-04-06 22:25:05.233 11377-11377/br.com.bichoramaapp E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.coordinatorlayout.widget.CoordinatorLayout" on path: DexPathList[[zip file "/data/app/br.com.bichoramaapp-EZ3_WGldYovzpp51ICOP7Q==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.bichoramaapp-EZ3_WGldYovzpp51ICOP7Q==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 27 more`

**Comment by rdlabo** [comment]
Please use version 2.0.2. I already checked in Android X.
